### ISSUE TITLE
When playing with this add-on enabled, the client crashes after about 30 minutes to an hour.

### ISSUE THREAD

**Issue by archleglusus** [leoaviana/ConsolePortLK#2] opened 2024-10-15 11:01 UTC
Google translation. Excuse me.

When playing with this add-on enabled, the client crashes after about 30 minutes to an hour.
I tried various things, including removing all other add-ons, but the crash still occurs when I enable Console PortLK.
I have clumsy arms, so I'm very happy to be able to use a controller. Waiting for completion.

**Comment by Gracecamelot** [comment] 2024-10-15 11:07
Hi, 

Really love your work! Like the commenter above, I also get severe arm pains when playing with KB&M, so to able to use a controller is a godsend. 

Unfortunately, I also experience that the 3.3.5a client freezes or hangs after about 30-40 minutes to an hour.

I really hope that there is something you can do, as being able to play wrath comfortably with a controller is like the best thing ever!

**Comment by leoaviana** [comment] 2024-10-18 00:16
Hello, I remember having this issue when I was porting but I couldn't reproduce anymore because it used to happen more often (like 10 minutes ingame) however I've never tested it for a long period of time, at the moment I have no time to take a look on this issue because of school. I'll have a break by the end of next week and then I will try to look into it.

But if you guys have time and if you can check it for me, try disabling all other consoleport addons and keep only the core addon (ConsolePortLK) to see if the issue is at the core or at the other addins (like ConsolePortBar or ConsolePortUI_Menu for example).

**Comment by Gracecamelot** [comment] 2024-10-18 09:39
Hi, 
Yes - thank you very much!
I have tested similarly as Arch, and can confirm the same - I have currently run the game for ~3 hours with just the core, and have had no crashes so far.

**Comment by archleglusus** [comment] 2024-10-18 12:45
Hi Gracecamelot.
thank you very much!
I have some bad news. After that, when I turned on the [Action bar], the client started crashing after about 30 to 40 minutes.

**Comment by Gracecamelot** [comment] 2024-10-18 14:09
I have been running with the [Action Bar] for ~2 hours now with no crashes. However, I got a crash after 45 mins with [UI Menu] turned on.

**Comment by leoaviana** [comment] 2024-10-18 18:08
Thank you all for your test results.

The cause of the problem won't be easy to find, as the game hangs with no output or Lua errors, and the issue only occurs about every 45 minutes. It could be due to bad porting on my part, a WoW API issue, or a memory leak. If the issue lies with ConsolePortBar, I already have an idea of where to look in the code because there are some hacky UI and action bar workarounds.

In the meantime, try playing without ConsolePortBar. I'll try to take a look at it this weekend, but I can't guarantee I'll have the time to do it,

**Comment by archleglusus** [comment] 2024-10-21 16:53
Hi leoaviana.
thank you very much!

Over the past few days, I have almost completed my own verification of ConsolePortLK.

I first played the game for a full day and a half with the ConsolePortLK add-on, LK Advanced, and LK Keyboard turned on. At that time, I went to the Dungeon Finder and other places and did not experience any crashes at all.

I then played the game for a full day with only the LK Action Bar turned off and everything else turned on, and again, no crashes occurred at all.

However, when I turned on the LK Action Bar, the crashes still occurred frequently.

I am now playing with only the Action Bar replaced with something as easy to see as possible.

I hope this post will give some insight to the author.

Translated with DeepL.com (free version)

**Comment by John-Laser** [comment] 2024-11-20 14:17
Just found this awesome addon and can confirm the same issue as posters above.
Great work! Do you perhaps have any ETA on when you expect to solve it - really looking forward to playing my favorite wow expansion with this addon! Thank you

**Comment by c3t1nn** [comment] 2024-11-20 19:39
@leoaviana looks like your fan base ise growing!)) hope you can have some time to take a look on issue,  console port is highly addictive and after some time, i really dont want to play with. thx a lot for your hard work once again!

**Comment by linktavo** [comment] 2024-11-25 23:07
Hey this project is amazing!! Sadly I'm reporting the same issue, I have tested on different machines and Windows version, and it happened as well.

Hopefully you could have time to solve this and give happiness to your fandom haha, thanks in advance!!

**Comment by leoaviana** [comment] 2024-11-26 01:57
Yeah, I'm sorry for the long time without answers. I just got my new laptop yesterday because my old one wasn't working anymore so now I can finally work on some stuff. regarding this issue, I believe that the problem lies in the custom round cooldown frame which is used both in ConsolePort's Utility Ring and ConsolePortBar.

I think ConsolePort does not crash with ConsolePortBar disabled because the utility ring is not used very often, however ConsolePortBar is always updating the cooldown frames and I think the memory leak is there somewhere, but I cannot test it at least for now because I am still doing the basic setup in my new laptop.

What I can do now is edit the ActionButton.xml to remove round cooldowns for testing and if you guys can test if it changes something it will be great.

[ConsolePort.zip](https://github.com/user-attachments/files/17911486/ConsolePort.zip)

Just replace your ConsolePort folder inside your game AddOns folder.

**Comment by linktavo** [comment] 2024-11-27 00:00
@leoaviana Man!! Thanks for your response, I have tested over 3 horas of playing with this Consoleport folder and so far working without crashing the game, I just want to mention that I'm not able to see the cooldown of the spells and it has also some square when you are pressing the bottom in the control spell bar.

Big thanks for be that guy that allows to play again <3


![IMG_8222 JPG_compressed](https://github.com/user-attachments/assets/e81ca777-e677-4f7a-b5e5-9233ef1c7de3)

**Comment by Gracecamelot** [comment] 2024-11-27 14:23
Can confirm as well - been playing 3-4 hours yesterday with no crashes so far.

**Comment by c3t1nn** [comment] 2024-11-28 21:08
can confirm the rest. i have nearly played a 4 hour session, and that followed by 3 another. no crush at all!
only black square boxes, behind buttons and i guess they are here for cds. for cc i am using sexy cooldowns addon, so i didnt bothered by this square boxes. yet, if possible numbers for cds can be nice to ig.
thank you so much for your port and support on it! this one made love wow again, thank you so much!!

**Comment by leoaviana** [comment] 2024-11-28 23:22
Yeah what I provided earlier is not a fix, I just removed the round cooldowns which expectedly messed up with all cooldowns to see if the issue was with the cooldown frame implementation. I've been trying to find what is causing the crashes and found some weird animation duration stuff.

The biggest issue for me is time to test the game, I've been testing the game for nearly 1 hour and I couldn't reproduce any crash, can someone test this to see if it will work?

[
[ConsolePort.zip](https://github.com/user-attachments/files/17952833/ConsolePort.zip)
](url)

Just replace your ConsolePort folder inside your game AddOns folder with the one that is inside the attached zip file above.

**Comment by c3t1nn** [comment] 2024-11-29 09:44
> Yeah what I provided earlier is not a fix, I just removed the round cooldowns which expectedly messed up with all cooldowns to see if the issue was with the cooldown frame implementation. I've been trying to find what is causing the crashes and found some weird animation duration stuff.
> 
> The biggest issue for me is time to test the game, I've been testing the game for nearly 1 hour and I couldn't reproduce any crash, can someone test this to see if it will work?
> 
> [ConsolePort.zip](https://github.com/user-attachments/files/17952833/ConsolePort.zip)
> 
> Just replace your ConsolePort folder inside your game AddOns folder with the one that is inside the attached zip file above.

i can go for that, you have any kind of debug implemented on it for logs? just in case if it crashes again, ig that would be easy for you to see whats happening. just an idea tho.

**Comment by linktavo** [comment] 2024-11-29 14:41
> Yeah what I provided earlier is not a fix, I just removed the round cooldowns which expectedly messed up with all cooldowns to see if the issue was with the cooldown frame implementation. I've been trying to find what is causing the crashes and found some weird animation duration stuff.
> 
> The biggest issue for me is time to test the game, I've been testing the game for nearly 1 hour and I couldn't reproduce any crash, can someone test this to see if it will work?
> 
> [ConsolePort.zip](https://github.com/user-attachments/files/17952833/ConsolePort.zip)
> 
> Just replace your ConsolePort folder inside your game AddOns folder with the one that is inside the attached zip file above.

Yesterday I tested the update you have provided to us, and so far any crashes, being played for an hour and a half that was the time I had to tested. I will inform any issue if it occurs during the weekend.

**Comment by Gracecamelot** [comment] 2024-12-16 09:57
I have tested extensively - totaling 20+ hours - and so far I have had no crashes with the latest version :)

**Comment by leoaviana** [comment] 2024-12-17 01:11
> I have tested extensively - totaling 20+ hours - and so far I have had no crashes with the latest version :)

Thank you for reporting, yeah I did some testing and some bugfixes myself this weekend too and I couldn't reproduce the issue anymore.

So, the issue is fixed in the new [1.1.0 release.](https://github.com/leoaviana/WoWmapperX/releases/tag/1.1.0)

**Closed by leoaviana** 2024-12-17 01:11 UTC
